package rs.ac.bg.etf.pp1;

import java_cup.runtime.*;
import rs.ac.bg.etf.pp1.ast.*;

parser code {:

	boolean errorDetected;

	public void report_fatal_error(String message, Object info) throws java.lang.Exception {
		done_parsing();
		report_error(message, info);
	}
	
	public void syntax_error(Symbol current_token) {
		report_error("Sintaksna greska ", current_token);
	}
	
	public void unrecovered_syntax_error(Symbol current_token) throws java.lang.Exception {
		report_fatal_error("Fatalna greska ", current_token);
	}
	
	public void report_error(String message, Object info) {
		errorDetected = true;
		
		StringBuilder msg = new StringBuilder(message);
		
		if (info instanceof Symbol) {
			msg.append("na liniji ").append(((Symbol) info).left);
		}
		
		System.err.println(msg.toString());
	}
		
:}

init with {:
	errorDetected = false;
:}	
		
scan with {:
	Symbol s = this.getScanner().next_token();
	
	if (s != null && s.value != null) {
		System.out.println(s.toString() + " " + s.value.toString());
	}
	
	return s;
:}



terminal PROG;
terminal IF, ELSE, WHILE, FOREACH, LAMBDA, CONTINUE, BREAK;
terminal CONST, VOID, RETURN;
terminal PRINT, READ;
terminal CLASS, EXTENDS, NEW, DOT;

terminal EQUAL, PLUS, MINUS, MUL, DIV, MOD, INC, DEC;
terminal EQ, NE, GT, GE, LT, LE, AND, OR;
terminal SEMI, COMMA;
terminal LPAREN, RPAREN, LCURLY, RCURLY, LSQUARE, RSQUARE;

terminal Integer NUMCONST, CHARCONST, BOOLCONST;

terminal String IDENT;



nonterminal Program;
nonterminal rs.etf.pp1.symboltable.concepts.Obj ProgramHeader;

nonterminal rs.etf.pp1.symboltable.concepts.Struct Type;

nonterminal DeclStmtList, DeclStmt;

nonterminal ConstDeclStmt, ConstDeclList, ConstDecl;

nonterminal VarDeclStmtList, VarDeclStmt, VarDeclList, VarDecl, VarArray;

nonterminal rs.etf.pp1.symboltable.concepts.Struct ClassDecl;
nonterminal rs.ac.bg.etf.pp1.VirtualMethods ClassHeader;
nonterminal ClassParent, ClassMethods, ConstructorDeclList;
nonterminal rs.etf.pp1.symboltable.concepts.Obj ConstructorDecl, ConstructorSignature;

nonterminal rs.etf.pp1.symboltable.concepts.Obj MethodSignature, MethodDecl;
nonterminal MethodDeclList, MethodType;

nonterminal FormPars, FormParList, FormPar, FormParArray;

nonterminal StatementList, Statement;
nonterminal CondStart, ElseHeader, WhileHeader;
nonterminal rs.etf.pp1.symboltable.concepts.Obj ForeachHeader;
nonterminal WidthOptional;

nonterminal rs.etf.pp1.symboltable.concepts.Obj Designator, LoadDesignatorArray;
nonterminal DesignatorStatement, PostfixOp;
nonterminal rs.ac.bg.etf.pp1.ObjList DesignatorList;

nonterminal MethodCall;
nonterminal rs.etf.pp1.symboltable.concepts.Obj MethodDesignator;
nonterminal rs.ac.bg.etf.pp1.ObjList ActPars, ExprList;

nonterminal rs.etf.pp1.symboltable.concepts.Struct Expr, TermFirst, Term;
nonterminal rs.etf.pp1.symboltable.concepts.Obj Factor, NewClass;

nonterminal Condition, CondTerm, CondFact, Or;

nonterminal rs.ac.bg.etf.pp1.OpCode AddOp, MulOp, RelOp;
nonterminal AssignOp;



precedence left ELSE;



Program 				::= (Program) ProgramHeader DeclStmtList LCURLY MethodDeclList RCURLY;

ProgramHeader			::= (ProgramHeader) PROG IDENT:progName;

//------------------------------------------------------------------------

Type					::= (Type) IDENT:typeName;

//------------------------------------------------------------------------
	
DeclStmtList			::= (DeclStmtYes) DeclStmt DeclStmtList
							|
							(DeclStmtNo) /* epsilon */
							;
						
DeclStmt				::= (DeclStmtConst) ConstDeclStmt
							|
							(DeclStmtVar) VarDeclStmt
							|
							(DeclStmtClass) ClassDecl
							;
							
//------------------------------------------------------------------------							
	
ConstDeclStmt			::= (ConstDeclStmt) CONST Type ConstDeclList SEMI;
	
ConstDeclList 			::= (ConstDeclMultiple) ConstDeclList COMMA ConstDecl
					  		|
					  		(ConstDeclSingle) ConstDecl
					  		;
	
ConstDecl 				::= (ConstDeclNum) IDENT:constName EQUAL NUMCONST:constVal
							|
							(ConstDeclChar) IDENT:constName EQUAL CHARCONST:constVal
							|
							(ConstDeclBool) IDENT:constName EQUAL BOOLCONST:constVal
							;
							
//------------------------------------------------------------------------							
					
VarDeclStmtList			::= (VarDeclStmtYes) VarDeclStmt VarDeclStmtList
							|
							(VarDeclStmtNo) /* epsilon */
							;						
					
VarDeclStmt				::= (VarDeclStmtValid) Type VarDeclList SEMI
							|
							(VarDeclStmtErrorComma) error COMMA VarDeclList SEMI
							|
							(VarDeclStmtErrorSemi) error SEMI
							;

VarDeclList				::= (VarDeclMultiple) VarDecl COMMA VarDeclList
							|
							(VarDeclSingle) VarDecl
							;
					
VarDecl					::= (VarDecl) IDENT:varName VarArray;

VarArray 				::= (VarArrayYes) LSQUARE RSQUARE
							|
							(VarArrayNo) /* epsilon */
							;												

//------------------------------------------------------------------------

ClassDecl				::= (ClassDecl) ClassHeader LCURLY VarDeclStmtList ClassMethods RCURLY;

ClassHeader				::= (ClassHeader) CLASS IDENT:className ClassParent;

ClassParent				::= (ClassParentYes) EXTENDS Type
							|
							(ClassParentNo) /* epsilon */
							|
							(ClassParentError) error
							;						
							
ClassMethods			::= (ClassMethodsYes) LCURLY ConstructorDeclList MethodDeclList RCURLY
							|
							(ClassMethodsNo) /* epsilon */
							;							
							
ConstructorDeclList		::= (ConstructorDeclYes) ConstructorDeclList ConstructorDecl
							|
							(ConstructorDeclNo) /* epsilon */
							;

ConstructorDecl			::= (ConstructorDecl) ConstructorSignature VarDeclStmtList LCURLY StatementList RCURLY;							
	
ConstructorSignature	::= (ConstructorSignature) 	IDENT:className LPAREN FormPars;
							
//------------------------------------------------------------------------
					
MethodDeclList			::= (MethodDeclYes) MethodDecl MethodDeclList
							|
							(MethodDeclNo) /* epsilon */
							;
					
MethodDecl				::= (MethodDecl) MethodSignature VarDeclStmtList LCURLY StatementList RCURLY;

MethodSignature			::= (MethodSignature) MethodType IDENT:methodName LPAREN FormPars;

MethodType				::= (VoidYes) VOID
							|
							(VoidNo) Type
							;
							
//------------------------------------------------------------------------							
							
FormPars				::= (FormParsYes) FormParList
							|
							(FormParsNo) RPAREN
							;
							
FormParList				::= (FormParMultiple) FormPar COMMA FormParList
							|
							(FormParSingle) FormPar RPAREN
							|
							(FormParErrorComma) error COMMA FormParList
							|
							(FormParErrorParen) error RPAREN
							;
							
FormPar					::= (FormPar) Type IDENT:formParName FormParArray;

FormParArray			::= (FormParArrayYes) LSQUARE RSQUARE
							|
							(FormParArrayNo) /* epsilon */
							;	

//------------------------------------------------------------------------

StatementList			::= (StatementYes) Statement StatementList
							|
							(StatementNo) /* epsilon */
							;
							
Statement				::= (StatementDesignator) DesignatorStatement
							|
							(StatementIfElse) IF CondStart LPAREN Condition Statement ElseHeader Statement
							|
							(StatementIf) IF CondStart LPAREN Condition Statement
							|
							(StatementWhile) WhileHeader CondStart LPAREN Condition Statement
							|
							(StatementBreak) BREAK SEMI
							|
							(StatementContinue) CONTINUE SEMI
							|
							(StatementReturnExpr) RETURN Expr SEMI
							|
							(StatementReturnVoid) RETURN SEMI
							|
							(StatementRead) READ LPAREN Designator RPAREN SEMI
							|
							(StatementPrint) PRINT LPAREN Expr WidthOptional RPAREN SEMI
							|
							(StatementForeach) ForeachHeader LAMBDA Statement RPAREN SEMI
							|
							(StatementBlock) LCURLY StatementList RCURLY
							;

CondStart				::= (CondStart) /* epsilon */;							
							
ElseHeader				::= (ElseHeader) ELSE;								
							
WhileHeader				::= (WhileHeader) WHILE;												
							
WidthOptional			::= (WidthYes) COMMA NUMCONST:width
							|
							(WidthNo) /* epsilon */
							;
							
ForeachHeader			::= (ForeachHeader) Designator DOT FOREACH LPAREN IDENT:element;													 												

//------------------------------------------------------------------------											

DesignatorStatement		::= (DesignatorAssignOp) Designator AssignOp Expr SEMI
							|
							(DesignatorAssignOpError) error SEMI
							|
							(DesignatorMethod) MethodCall SEMI
							|
							(DesignatorPostfixOp) Designator PostfixOp SEMI
							|
							(DesignatorMultiple) LSQUARE DesignatorList RSQUARE AssignOp Designator SEMI
							;	

Designator				::= (DesignatorClass) Designator DOT IDENT:fieldName
							|
							(DesignatorArray) LoadDesignatorArray LSQUARE Expr RSQUARE
							|
							(DesignatorIdent) IDENT:designatorName
							;
							
LoadDesignatorArray		::= (LoadDesignatorArray) Designator;							
							
PostfixOp				::= (PostfixInc) INC
							|
							(PostfixDec) DEC
							;													
							
DesignatorList			::= (DesignatorPresent) DesignatorList COMMA Designator
							|
							(DesignatorSkip) DesignatorList COMMA
							|
							(DesignatorDone) Designator
							|
							(DesignatorNone) /* epsilon */
							;				
							
//------------------------------------------------------------------------	

MethodCall				::= (MethodCall) MethodDesignator LPAREN ActPars RPAREN;

MethodDesignator		::= (MethodDesignator) Designator;					
							
ActPars					::= (ActParsYes) ExprList
							|
							(ActParsNo) /* epsilon */
							;													

ExprList				::= (ExprMultiple) ExprList COMMA Expr
							|
							(ExprSingle) Expr
							;

//------------------------------------------------------------------------

Expr					::= (TermSingle) TermFirst
							|
							(TermMultiple) Expr AddOp Term
							;						
							
//------------------------------------------------------------------------
							
TermFirst				::= (TermPositive) Term
							|
							(TermNegative) MINUS Term
							;	
							
Term 					::= (FactorSingle) Factor
							|
							(FactorMultiple) Term MulOp Factor;	

//------------------------------------------------------------------------
																				
Factor					::= (FactorDesignator) Designator
							|
							(FactorDesignatorMethod) MethodCall
							|
							(FactorNum) NUMCONST:constVal
							|
							(FactorChar) CHARCONST:constVal
							|
							(FactorBool) BOOLCONST:constVal
							|
							(FactorNewClass) NewClass LPAREN ActPars RPAREN
							|
							(FactorNewArray) NEW Type LSQUARE Expr RSQUARE
							|
							(FactorParen) LPAREN Expr RPAREN
							;	
							
NewClass				::= (NewClass) NEW Type;							

//------------------------------------------------------------------------

Condition				::= (CondTermMultiple) CondTerm Or Condition
							|
							(CondTermSingle) CondTerm RPAREN
							|
							(ConditionError) error RPAREN
							;
							
CondTerm				::= (CondFactMultiple) CondFact AND CondTerm
							|
							(CondFactSingle) CondFact
							;
							
CondFact				::= (CondExpr) Expr
							|
							(CondRelOp) Expr RelOp Expr
							;	
							
Or						::= (Or) OR;																			
							
//------------------------------------------------------------------------

AssignOp				::= (AssignOp) EQUAL;	

AddOp					::= (AddOpAdd) PLUS
							|
							(AddOpSub) MINUS
							;	
							
MulOp					::= (MulOpMul) MUL
							|
							(MulOpDiv) DIV
							|
							(MulOpRem) MOD
							;						
							
RelOp					::= (RelOpEq) EQ
							|																		
							(RelOpNe) NE
							|
							(RelOpGt) GT
							|
							(RelOpGe) GE
							|
							(RelOpLt) LT
							|
							(RelOpLe) LE
							;						